// ===== 9. DELOVI PROIZVODA (svi jezici) =====
const productParts = {
    // ===== SRPSKI =====
    sr: {
        "Pileće": ["Gril pile", "Pile celo", "Ceo batak", "Karabatak", "Donji batak", "Belo (grudi)", "File", "Leđa", "Krilca", "Medaljoni", "Nugati", "Panirani odrezak", "Mleveno", "Za supu", "Ostalo"],
        "Ćureće": ["Ceo batak", "Karabatak", "Donji batak", "Rolovani batak", "Odresci od bataka", "Belo (grudi)", "Krilca", "Leđa", "Krila", "Za supu", "Mleveno", "Ostalo"],
        "Guska": ["Belo (grudi)", "Ceo batak", "Karabatak", "Donji batak", "Krilca", "Leđa", "Vrat", "Jetra (foie gras)", "Gušćja mast", "Mleveno", "Za supu", "Ostalo"],
        "Patka": ["Belo (grudi)", "Ceo batak", "Karabatak", "Donji batak", "Krilca", "Leđa", "Vrat", "Pačija mast", "Mleveno", "Jetra", "Za supu", "Ostalo"],
        "Svinjsko": ["Šnicla", "Karmenadla", "Vrat", "But", "Kare", "Rebra", "Grudi", "Plećka", "Podplećka", "Kolenica", "Mleveno", "Usitnjen", "Za supu", "Ostalo"],
        "Jagnjeće": ["Glava", "Vrat", "Plećka", "Slabine", "Grudi", "Bubrežnjak", "But", "Kolenica", "Ostalo"],
        "Ovčije": ["Glava", "Vrat", "Plećka", "Slabine", "Grudi", "Bubrežnjak", "But", "Kolenica", "Ostalo"],
        "Juneće": ["Biftek", "Vrat - zaplecak", "Prsa", "Lopatica", "Kolenica", "Rebra", "Potrbušina", "T-bone steak", "Ramstek", "Rib-Eye", "Rep", "Ostalo"],
        "Govedina": ["Karmedla", "Biftek", "Vrat", "Podplećka", "Grudi", "Kolenica", "Rebra", "Slabine", "Leđa", "Trbušina", "But", "Ostalo"],
        "Od bika": ["But", "Plećka", "Kare (leđa)", "Prsa i rebra", "Lopatica", "Vrat", "Slabina", "Rep", "Ostalo"],
        "Konjsko": ["But", "Plećka", "Kare (leđa)", "Vrat", "Prsa i rebra", "Biftek", "Ramstek", "Mleveno meso", "Ostalo"],
        "Zečije": ["Zadnji but", "Prednji but", "File (leđa)", "Rebra", "Ostalo"],
        "Prepelica": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Fazan": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Jarebica": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Golub": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Divlji zec": ["Zadnji but", "Prednji but", "File (leđa)", "Rebra", "Ostalo"],
        "Divlja patka": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Divlja guska": ["Celo meso", "Grudi (fileti)", "Bataci", "Jetra", "Ostalo"],
        "Jelen": ["But", "File (leđa)", "Biftek", "Rebra", "Grudi", "Plećka", "Kolenica", "Usitnjeno", "Ostalo"],
        "Srna": ["But", "File (leđa)", "Biftek", "Rebra", "Grudi", "Plećka", "Kolenica", "Usitnjeno", "Ostalo"],
        "Divokoza": ["But", "File (leđa)", "Biftek", "Rebra", "Grudi", "Plećka", "Kolenica", "Usitnjeno", "Ostalo"],
        "Irvas": ["But", "File (leđa)", "Biftek", "Rebra", "Grudi", "Plećka", "Kolenica", "Usitnjeno", "Ostalo"],
        "Los": ["But", "File (leđa)", "Biftek", "Rebra", "Grudi", "Plećka", "Kolenica", "Usitnjeno", "Ostalo"],
        "Divlja svinja": ["But", "Plećka", "Rebra", "Slanina", "Kolenica", "Vrat", "Glava", "Ostalo"],
        "Bizon": ["But", "Plećka", "Biftek", "Ramstek", "Rebra", "Slabina", "Vrat", "Kolenica", "Ostalo"],
        "Kamila": ["But", "Plećka", "File (slabine)", "File (leđa)", "Rebra", "Grudi", "Vrat", "Grba", "Ostalo"],
        "Lama": ["But", "Plećka", "File (leđa i slabine)", "Rebra", "Vrat", "Ostalo"],
        "Alpaka": ["But", "Plećka", "File (leđa i slabine)", "Rebra", "Vrat", "Ostalo"],
        "Kengur": ["But", "Plećka", "File (leđa i slabine)", "Rebra", "Rep", "Ostalo"],
        "Krokodil/Aligator": ["Rep", "File (leđa)", "Butine", "Ostalo"],
        "Zmija": ["Trup (prstenovi)", "Ostalo"],
        "Gušter": ["Rep", "Leđa", "Butine", "Ostalo"],
        "Morska": ["Losos", "Tuna", "Sardina", "Bakalar", "Oslić", "Skuša", "Brancin", "Orada", "Halibut", "Haringa", "Inćuni", "Kirnja", "Ostalo"],
        "Slatkovodna": ["Šaran", "Pastrmka", "Som", "Grgeč", "Smuđ", "Tilapija", "Pangasijus", "Jesetra", "Štuka", "Beli amur", "Pirarukus", "Ostalo"],
        "Plodovi mora": ["Škampi", "Sipa", "Jakobove kapice", "Venerina školjka", "Dagnje", "Kamenice", "Školjke", "Rak", "Hobotnica", "Lignja", "Morski ježevi", "Morski krastavci", "Abalone", "Ostalo"],
        "Mleko": ["Mleko", "Kefir", "Kisela pavlaka", "Slatka pavlaka", "Pavlaka za kuvanje", "Ostalo"],
        "Mlečne prerađevine": ["Urda", "Mladi sir", "Krem sir", "Gouda", "Edamer", "Trapist", "Kačkavalj", "Parmezan", "Gorgonzola", "Rokfor", "Halloumi", "Ostalo"],
        "Sveže": ["Grašak", "Boranija", "Karfiol", "Brokoli", "Bundeva", "Paradajz", "Krastavac", "Paprika", "Ostalo"],
        "Termički obrađeno": ["Grašak", "Boranija", "Kukuruz", "Karfiol", "Brokoli", "Paprika", "Tikvice", "Spanać", "Ostalo"],
        "Zamrznuto": ["Grašak", "Boranija", "Kukuruz", "Karfiol", "Brokoli", "Paprika", "Tikvice", "Spanać", "Ostalo"],
        "Voće": ["Kajsija", "Kruška", "Višnja", "Pekmez od jagoda", "Šljivov pekmez", "Trešnja", "Pekmez od malina", "Dunja", "Ananas", "Pekmez od manga", "Ostalo"],
        "Povrće": ["Kiseli krastavci", "Kisela paprika", "Paradajz pire", "Cvekla", "Ajvar", "Turšija", "Kiseli kupus", "Ostalo"],
        "Testo": ["Hleb", "Raženi hleb", "Čabata", "Kukuruzni hleb", "Baguette", "Pšenično brašno", "Integralno brašno", "Heljdino brašno", "Pirinčano brašno", "Začini", "Ostalo"],
        "Slatkiši": ["Kolači", "Torte", "Peciva", "Sladoled", "Čokolada", "Bombone", "Ostalo"],
        "Voda": ["Mineralna", "Negazirana", "Gazirana", "Ostalo"],
        "Vino": ["Crno", "Belo", "Roze", "Ostalo"],
        "Sok": ["Voćni", "Povrtni", "Ostalo"],
        "Žestoka pića": ["Rakija", "Votka", "Viski", "Ostalo"],
        "Pivo": ["Tamno", "Svetlo", "Ostalo"],
        "Sanitar": ["Pranje prozora", "Pranje posuđa", "Pranje podova", "Sredstvo za kupatilo", "Ostalo"],
        "Lična higijena": ["Dezodorans", "Brijač", "Šminka", "Sapun", "Šampon", "Krema", "Ostalo"],
        "Pribor": ["Kantica", "Kofa", "Krpa za prašinu", "Metla", "Ostalo"],
        "Ostalo": ["Napomena: Unesite naziv proizvoda"]
    },
    
    // ===== ENGLISH =====
    en: {
        "Chicken": ["Grilled chicken", "Whole chicken", "Whole leg", "Thigh fillet", "Drumstick", "Breast", "Fillet", "Back", "Wings", "Medallions", "Nuggets", "Breaded cutlet", "Minced", "For soup", "Other"],
        "Turkey": ["Whole leg", "Thigh fillet", "Drumstick", "Rolled thigh", "Thigh steaks", "Breast", "Wings", "Back", "Wing tips", "For soup", "Minced", "Other"],
        "Goose": ["Breast", "Whole leg", "Thigh fillet", "Drumstick", "Wings", "Back", "Neck", "Liver (foie gras)", "Goose fat", "Minced", "For soup", "Other"],
        "Duck": ["Breast", "Whole leg", "Thigh fillet", "Drumstick", "Wings", "Back", "Neck", "Duck fat", "Minced", "Liver", "For soup", "Other"],
        "Pork": ["Schnitzel", "Chop", "Neck", "Leg", "Loin", "Ribs", "Belly", "Shoulder", "Picnic shoulder", "Hock", "Minced", "Ground", "For soup", "Other"],
        "Lamb": ["Head", "Neck", "Shoulder", "Loin", "Breast", "Kidney", "Leg", "Shank", "Other"],
        "Sheep": ["Head", "Neck", "Shoulder", "Loin", "Breast", "Kidney", "Leg", "Shank", "Other"],
        "Veal": ["Steak", "Neck", "Breast", "Shoulder", "Shank", "Ribs", "Flank", "T-bone steak", "Rump steak", "Rib-Eye", "Tail", "Other"],
        "Beef": ["Steak", "Steak", "Neck", "Shoulder", "Breast", "Shank", "Ribs", "Loin", "Back", "Belly", "Leg", "Other"],
        "Bull": ["Leg", "Shoulder", "Loin", "Breast and ribs", "Shoulder", "Neck", "Flank", "Tail", "Other"],
        "Horse": ["Leg", "Shoulder", "Loin", "Neck", "Breast and ribs", "Steak", "Rump steak", "Minced meat", "Other"],
        "Rabbit": ["Hind leg", "Front leg", "Fillet", "Ribs", "Other"],
        "Quail": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Pheasant": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Partridge": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Pigeon": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Hare": ["Hind leg", "Front leg", "Fillet", "Ribs", "Other"],
        "Wild duck": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Wild goose": ["Whole meat", "Breast fillets", "Legs", "Liver", "Other"],
        "Deer": ["Leg", "Fillet", "Steak", "Ribs", "Breast", "Shoulder", "Shank", "Ground", "Other"],
        "Roe deer": ["Leg", "Fillet", "Steak", "Ribs", "Breast", "Shoulder", "Shank", "Ground", "Other"],
        "Wild goat": ["Leg", "Fillet", "Steak", "Ribs", "Breast", "Shoulder", "Shank", "Ground", "Other"],
        "Reindeer": ["Leg", "Fillet", "Steak", "Ribs", "Breast", "Shoulder", "Shank", "Ground", "Other"],
        "Moose": ["Leg", "Fillet", "Steak", "Ribs", "Breast", "Shoulder", "Shank", "Ground", "Other"],
        "Wild boar": ["Leg", "Shoulder", "Ribs", "Bacon", "Shank", "Neck", "Head", "Other"],
        "Bison": ["Leg", "Shoulder", "Steak", "Rump steak", "Ribs", "Loin", "Neck", "Shank", "Other"],
        "Camel": ["Leg", "Shoulder", "Fillet", "Fillet", "Ribs", "Breast", "Neck", "Hump", "Other"],
        "Llama": ["Leg", "Shoulder", "Fillet", "Ribs", "Neck", "Other"],
        "Alpaca": ["Leg", "Shoulder", "Fillet", "Ribs", "Neck", "Other"],
        "Kangaroo": ["Leg", "Shoulder", "Fillet", "Ribs", "Tail", "Other"],
        "Crocodile/Alligator": ["Tail", "Fillet", "Legs", "Other"],
        "Snake": ["Body rings", "Other"],
        "Lizard": ["Tail", "Back", "Legs", "Other"],
        "Sea": ["Salmon", "Tuna", "Sardine", "Cod", "Hake", "Mackerel", "Seabass", "Gilthead", "Halibut", "Herring", "Anchovy", "Grouper", "Other"],
        "Freshwater": ["Carp", "Trout", "Catfish", "Perch", "Pikeperch", "Tilapia", "Pangasius", "Sturgeon", "Pike", "Grass carp", "Arapaima", "Other"],
        "Seafood": ["Shrimp", "Cuttlefish", "Scallops", "Clams", "Mussels", "Oysters", "Shellfish", "Crab", "Octopus", "Squid", "Sea urchins", "Sea cucumbers", "Abalone", "Other"],
        "Milk": ["Milk", "Kefir", "Sour cream", "Sweet cream", "Cooking cream", "Other"],
        "Dairy processing": ["Curd", "Fresh cheese", "Cream cheese", "Gouda", "Edam", "Trappist", "Kashkaval", "Parmesan", "Gorgonzola", "Roquefort", "Halloumi", "Other"],
        "Fresh": ["Peas", "Green beans", "Cauliflower", "Broccoli", "Pumpkin", "Tomato", "Cucumber", "Pepper", "Other"],
        "Heat treated": ["Peas", "Green beans", "Corn", "Cauliflower", "Broccoli", "Pepper", "Zucchini", "Spinach", "Other"],
        "Frozen": ["Peas", "Green beans", "Corn", "Cauliflower", "Broccoli", "Pepper", "Zucchini", "Spinach", "Other"],
        "Fruits": ["Apricot", "Pear", "Sour cherry", "Strawberry jam", "Plum jam", "Sweet cherry", "Raspberry jam", "Quince", "Pineapple", "Mango jam", "Other"],
        "Vegetables": ["Pickles", "Pickled peppers", "Tomato puree", "Beetroot", "Ajvar", "Mixed pickles", "Sauerkraut", "Other"],
        "Dough": ["Bread", "Rye bread", "Ciabatta", "Corn bread", "Baguette", "Wheat flour", "Whole wheat flour", "Buckwheat flour", "Rice flour", "Spices", "Other"],
        "Sweets": ["Cakes", "Tarts", "Pastries", "Ice cream", "Chocolate", "Candy", "Other"],
        "Water": ["Mineral", "Still", "Sparkling", "Other"],
        "Wine": ["Red", "White", "Rosé", "Other"],
        "Juice": ["Fruit", "Vegetable", "Other"],
        "Spirits": ["Brandy", "Vodka", "Whisky", "Other"],
        "Beer": ["Dark", "Light", "Other"],
        "Sanitary": ["Window cleaner", "Dish soap", "Floor cleaner", "Bathroom cleaner", "Other"],
        "Personal hygiene": ["Deodorant", "Razor", "Makeup", "Soap", "Shampoo", "Cream", "Other"],
        "Equipment": ["Bucket", "Bucket", "Duster", "Broom", "Other"],
        "Other": ["Note: Enter product name"]
    },
    
    // ===== DEUTSCH =====
    de: {
        "Huhn": ["Grillhähnchen", "Ganzes Huhn", "Ganze Keule", "Keulenfilet", "Unterkeule", "Brust", "Filet", "Rücken", "Flügel", "Medaillons", "Nuggets", "Panierte Schnitzel", "Hackfleisch", "Für Suppe", "Andere"],
        "Truthahn": ["Ganze Keule", "Keulenfilet", "Unterkeule", "Roulade", "Keulenschnitzel", "Brust", "Flügel", "Rücken", "Flügelspitzen", "Für Suppe", "Hackfleisch", "Andere"],
        "Gans": ["Brust", "Ganze Keule", "Keulenfilet", "Unterkeule", "Flügel", "Rücken", "Hals", "Leber (Foie Gras)", "Gänseschmalz", "Hackfleisch", "Für Suppe", "Andere"],
        "Ente": ["Brust", "Ganze Keule", "Keulenfilet", "Unterkeule", "Flügel", "Rücken", "Hals", "Entenschmalz", "Hackfleisch", "Leber", "Für Suppe", "Andere"],
        "Schwein": ["Schnitzel", "Kotelett", "Nacken", "Keule", "Karre", "Rippen", "Bauch", "Schulter", "Unterschulter", "Haxe", "Hackfleisch", "Klein geschnitten", "Für Suppe", "Andere"],
        "Lamm": ["Kopf", "Hals", "Schulter", "Lende", "Brust", "Niere", "Keule", "Haxe", "Andere"],
        "Schaf": ["Kopf", "Hals", "Schulter", "Lende", "Brust", "Niere", "Keule", "Haxe", "Andere"],
        "Kalb": ["Steak", "Hals", "Brust", "Schulter", "Haxe", "Rippen", "Flanke", "T-Bone-Steak", "Rumpsteak", "Rib-Eye", "Schwanz", "Andere"],
        "Rind": ["Steak", "Steak", "Hals", "Schulter", "Brust", "Haxe", "Rippen", "Lende", "Rücken", "Bauch", "Keule", "Andere"],
        "Bulle": ["Keule", "Schulter", "Lende", "Brust und Rippen", "Schulter", "Hals", "Flanke", "Schwanz", "Andere"],
        "Pferd": ["Keule", "Schulter", "Lende", "Hals", "Brust und Rippen", "Steak", "Rumpsteak", "Hackfleisch", "Andere"],
        "Kaninchen": ["Hinterkeule", "Vorderkeule", "Filet", "Rippen", "Andere"],
        "Wachtel": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Fasan": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Rebhuhn": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Taube": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Hase": ["Hinterkeule", "Vorderkeule", "Filet", "Rippen", "Andere"],
        "Wildente": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Wildgans": ["Ganzes Fleisch", "Brustfilets", "Keulen", "Leber", "Andere"],
        "Hirsch": ["Keule", "Filet", "Steak", "Rippen", "Brust", "Schulter", "Haxe", "Hackfleisch", "Andere"],
        "Reh": ["Keule", "Filet", "Steak", "Rippen", "Brust", "Schulter", "Haxe", "Hackfleisch", "Andere"],
        "Wildziege": ["Keule", "Filet", "Steak", "Rippen", "Brust", "Schulter", "Haxe", "Hackfleisch", "Andere"],
        "Rentier": ["Keule", "Filet", "Steak", "Rippen", "Brust", "Schulter", "Haxe", "Hackfleisch", "Andere"],
        "Elch": ["Keule", "Filet", "Steak", "Rippen", "Brust", "Schulter", "Haxe", "Hackfleisch", "Andere"],
        "Wildschwein": ["Keule", "Schulter", "Rippen", "Speck", "Haxe", "Hals", "Kopf", "Andere"],
        "Bison": ["Keule", "Schulter", "Steak", "Rumpsteak", "Rippen", "Lende", "Hals", "Haxe", "Andere"],
        "Kamel": ["Keule", "Schulter", "Filet", "Filet", "Rippen", "Brust", "Hals", "Höcker", "Andere"],
        "Lama": ["Keule", "Schulter", "Filet", "Rippen", "Hals", "Andere"],
        "Alpaka": ["Keule", "Schulter", "Filet", "Rippen", "Hals", "Andere"],
        "Känguru": ["Keule", "Schulter", "Filet", "Rippen", "Schwanz", "Andere"],
        "Krokodil/Alligator": ["Schwanz", "Filet", "Keulen", "Andere"],
        "Schlange": ["Ringe", "Andere"],
        "Eidechse": ["Schwanz", "Rücken", "Keulen", "Andere"],
        "Meer": ["Lachs", "Thunfisch", "Sardine", "Kabeljau", "Seehecht", "Makrele", "Seebarsch", "Goldbrasse", "Heilbutt", "Hering", "Sardelle", "Zackenbarsch", "Andere"],
        "Süßwasser": ["Karpfen", "Forelle", "Wels", "Barsch", "Zander", "Tilapia", "Pangasius", "Stör", "Hecht", "Graskarpfen", "Arapaima", "Andere"],
        "Meeresfrüchte": ["Garnelen", "Tintenfisch", "Jakobsmuscheln", "Venusmuscheln", "Miesmuscheln", "Austern", "Schalen", "Krabbe", "Oktopus", "Kalmar", "Seeigel", "Seegurken", "Abalone", "Andere"],
        "Milch": ["Milch", "Kefir", "Sauerrahm", "Süße Sahne", "Kochsahne", "Andere"],
        "Milchverarbeitung": ["Topfen", "Frischkäse", "Frischkäse", "Gouda", "Edamer", "Trappist", "Kaschkawal", "Parmesan", "Gorgonzola", "Roquefort", "Halloumi", "Andere"],
        "Frisch": ["Erbsen", "Grüne Bohnen", "Blumenkohl", "Brokkoli", "Kürbis", "Tomate", "Gurke", "Paprika", "Andere"],
        "Wärmebehandelt": ["Erbsen", "Grüne Bohnen", "Mais", "Blumenkohl", "Brokkoli", "Paprika", "Zucchini", "Spinat", "Andere"],
        "Gefroren": ["Erbsen", "Grüne Bohnen", "Mais", "Blumenkohl", "Brokkoli", "Paprika", "Zucchini", "Spinat", "Andere"],
        "Früchte": ["Aprikose", "Birne", "Sauerkirsche", "Erdbeermarmelade", "Pflaumenmarmelade", "Süßkirsche", "Himbeermarmelade", "Quitte", "Ananas", "Mangomarmelade", "Andere"],
        "Gemüse": ["Essiggurken", "Eingelegte Paprika", "Tomatenmark", "Rote Bete", "Ajvar", "Gemischtes", "Sauerkraut", "Andere"],
        "Teig": ["Brot", "Roggenbrot", "Ciabatta", "Maisbrot", "Baguette", "Weizenmehl", "Vollkornmehl", "Buchweizenmehl", "Reismehl", "Gewürze", "Andere"],
        "Süßigkeiten": ["Kuchen", "Torten", "Gebäck", "Eiscreme", "Schokolade", "Bonbons", "Andere"],
        "Wasser": ["Mineral", "Still", "Sprudel", "Andere"],
        "Wein": ["Rot", "Weiß", "Rosé", "Andere"],
        "Saft": ["Frucht", "Gemüse", "Andere"],
        "Spirituosen": ["Schnaps", "Wodka", "Whisky", "Andere"],
        "Bier": ["Dunkel", "Hell", "Andere"],
        "Sanitär": ["Glasreiniger", "Spülmittel", "Bodenreiniger", "Badreiniger", "Andere"],
        "Persönliche Hygiene": ["Deodorant", "Rasierer", "Make-up", "Seife", "Shampoo", "Creme", "Andere"],
        "Ausrüstung": ["Eimer", "Eimer", "Staubwedel", "Besen", "Andere"],
        "Andere": ["Hinweis: Produktname eingeben"]
    },
    
    // ===== HUNGARY =====
    hu: {
        "Csirke": ["Grillcsirke", "Egész csirke", "Egész comb", "Comb filé", "Alsó comb", "Fehér hús (mell)", "Filé", "Hát", "Szárny", "Medál", "Nugget", "Rántott szelet", "Darált", "Leveshez", "Egyéb"],
        "Pulyka": ["Egész comb", "Comb filé", "Alsó comb", "Tekercs comb", "Comb szeletek", "Fehér hús (mell)", "Szárny", "Hát", "Szárnyak", "Leveshez", "Darált", "Egyéb"],
        "Libacomb": ["Fehér hús (mell)", "Egész comb", "Comb filé", "Alsó comb", "Szárny", "Hát", "Nyak", "Májas pástétom", "Libazsír", "Darált", "Leveshez", "Egyéb"],
        "Kacsa": ["Fehér hús (mell)", "Egész comb", "Comb filé", "Alsó comb", "Szárny", "Hát", "Nyak", "Kacsazsír", "Darált", "Máj", "Leveshez", "Egyéb"],
        "Sertéshús": ["Szelet", "Karfiol", "Nyak", "Comb", "Szűzérme", "Borda", "Mell", "Lapocka", "Karakas", "Csülök", "Darált", "Apróra vágott", "Leveshez", "Egyéb"],
        "Bárányhús": ["Fej", "Nyak", "Lapocka", "Gerinc", "Mell", "Vese", "Comb", "Csülök", "Egyéb"],
        "Juhhús": ["Fej", "Nyak", "Lapocka", "Gerinc", "Mell", "Vese", "Comb", "Csülök", "Egyéb"],
        "Borjúhús": ["Bifsztek", "Nyak - tarja", "Mell", "Lapocka", "Csülök", "Borda", "Has", "T-bone steak", "Rump steak", "Rib-Eye", "Farok", "Egyéb"],
        "Marhahús": ["Roston sült", "Bifsztek", "Nyak", "Karakas", "Mell", "Csülök", "Borda", "Gerinc", "Hát", "Has", "Comb", "Egyéb"],
        "Bikahús": ["Comb", "Lapocka", "Szűzérme (hát)", "Mell és borda", "Lapocka", "Nyak", "Ágyék", "Farok", "Egyéb"],
        "Lóhús": ["Comb", "Lapocka", "Szűzérme (hát)", "Nyak", "Mell és borda", "Bifsztek", "Rump steak", "Darált hús", "Egyéb"],
        "Nyúlhús": ["Hátsó comb", "Elülső comb", "Filé (hát)", "Borda", "Egyéb"],
        "Fürj": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Fácán": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Fogoly": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Galamb": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Vadnyúl": ["Hátsó comb", "Elülső comb", "Filé (hát)", "Borda", "Egyéb"],
        "Vadkacsa": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Vadliba": ["Egész hús", "Mell (filék)", "Combok", "Máj", "Egyéb"],
        "Szarvac": ["Comb", "Filé (hát)", "Bifsztek", "Borda", "Mell", "Lapocka", "Csülök", "Apróra vágott", "Egyéb"],
        "Őz": ["Comb", "Filé (hát)", "Bifsztek", "Borda", "Mell", "Lapocka", "Csülök", "Apróra vágott", "Egyéb"],
        "Vadkecske": ["Comb", "Filé (hát)", "Bifsztek", "Borda", "Mell", "Lapocka", "Csülök", "Apróra vágott", "Egyéb"],
        "Jávorszarvas": ["Comb", "Filé (hát)", "Bifsztek", "Borda", "Mell", "Lapocka", "Csülök", "Apróra vágott", "Egyéb"],
        "Rénszarvas": ["Comb", "Filé (hát)", "Bifsztek", "Borda", "Mell", "Lapocka", "Csülök", "Apróra vágott", "Egyéb"],
        "Vadkan": ["Comb", "Lapocka", "Borda", "Szalonna", "Csülök", "Nyak", "Fej", "Egyéb"],
        "Bölény": ["Comb", "Lapocka", "Bifsztek", "Rump steak", "Borda", "Ágyék", "Nyak", "Csülök", "Egyéb"],
        "Teve": ["Comb", "Lapocka", "Filé (ágyék)", "Filé (hát)", "Borda", "Mell", "Nyak", "Púp", "Egyéb"],
        "Láma": ["Comb", "Lapocka", "Filé (hát és ágyék)", "Borda", "Nyak", "Egyéb"],
        "Alpaka": ["Comb", "Lapocka", "Filé (hát és ágyék)", "Borda", "Nyak", "Egyéb"],
        "Kenguru": ["Comb", "Lapocka", "Filé (hát és ágyék)", "Borda", "Farok", "Egyéb"],
        "Krokodil/Alligátor": ["Farok", "Filé (hát)", "Combok", "Egyéb"],
        "Gyík": ["Farok", "Hát", "Combok", "Egyéb"],
        "Kígyó": ["Törzs (gyűrűk)", "Egyéb"],
        "Tengeri": ["Lazac", "Tonhal", "Szardínia", "Tőkehal", "Tőkehal", "Makréla", "Fogas", "Aranysügér", "Laposhal", "Herring", "Szardella", "Tőkehal", "Egyéb"],
        "Édesvízi": ["Ponty", "Pisztráng", "Harcsa", "Kárász", "Sügér", "Tilápia", "Pangász", "Tok", "Csuka", "Fehér amur", "Arapaima", "Egyéb"],
        "Tenger gyümölcsei": ["Garnéla", "Tintahal", "Kagyló", "Kagyló", "Kagyló", "Kagyló", "Kagyló", "Rák", "Polip", "Lília", "Tengeri sün", "Tengeri uborka", "Abalone", "Egyéb"],
        "Tej": ["Tej", "Kefir", "Tejföl", "Tejszín", "Főzőtejszín", "Egyéb"],
        "Tejfeldolgozások": ["Túró", "Friss sajt", "Krémsajt", "Gouda", "Edami", "Trappista", "Kaskavál", "Parmezán", "Gorgonzola", "Roquefort", "Halloumi", "Egyéb"],
        "Friss": ["Borsó", "Zöldbab", "Karfiol", "Brokkoli", "Tök", "Paradicsom", "Uborka", "Paprika", "Egyéb"],
        "Hőkezelt": ["Borsó", "Zöldbab", "Kukorica", "Karfiol", "Brokkoli", "Paprika", "Cukkini", "Spenót", "Egyéb"],
        "Fagyasztott": ["Borsó", "Zöldbab", "Kukorica", "Karfiol", "Brokkoli", "Paprika", "Cukkini", "Spenót", "Egyéb"],
        "Gyümölcs": ["Sárgabarack", "Körte", "Cseresznye", "Epres lekvár", "Szilvalekvár", "Cseresznye", "Málnalekvár", "Birsalma", "Ananász", "Mangó lekvár", "Egyéb"],
        "Zöldség": ["Savanyú uborka", "Savanyú paprika", "Paradicsompüré", "Cékla", "Ajvár", "Savanyúság", "Savanyú káposzta", "Egyéb"],
        "Tészta": ["Kenyér", "Rozskenyér", "Ciabatta", "Kukoricalepény", "Baguette", "Búzaliszt", "Teljes kiőrlésű liszt", "Hajdinaliszt", "Rizsliszt", "Fűszerek", "Egyéb"],
        "Édességek": ["Sütemények", "Torták", "Pékáru", "Fagylalt", "Csokoládé", "Cukorkák", "Egyéb"],
        "Víz": ["Ásványvíz", "Szénsavmentes", "Szénsavas", "Egyéb"],
        "Bor": ["Vörös", "Fehér", "Rozé", "Egyéb"],
        "Lé": ["Gyümölcslé", "Zöldséglé", "Egyéb"],
        "Tömény italok": ["Pálinka", "Vodka", "Whisky", "Egyéb"],
        "Sör": ["Barna", "Világos", "Egyéb"],
        "WC": ["Ablaktisztító", "Mosogatószer", "Padlótisztító", "Fürdőszobai tisztítószer", "Egyéb"],
        "Személyes higiénia": ["Dezodor", "Borotva", "Smink", "Szappan", "Sampon", "Krém", "Egyéb"],
        "Felszerelés": ["Vödör", "Vödör", "Poroló", "Seprű", "Egyéb"],
        "Egyéb": ["Megjegyzés: Írja be a termék nevét"]
    },
    
    // ===== UKRAJINSKI =====
    uk: {
        "Курятина": ["Ціла курка", "Грудка", "Стегно", "Гомілка", "Крило", "Філе", "Спина", "Медальйони", "Нагетси", "Панірований шніцель", "Фарш", "Для супу", "Інше"],
        "Індичка": ["Ціла індичка", "Грудка", "Стегно", "Крило", "Філе", "Спина", "Медальйони", "Для супу", "Фарш", "Інше"],
        "Гуска": ["Ціла гуска", "Грудка", "Стегно", "Крило", "Спина", "Шия", "Печінка", "Гусячий жир", "Фарш", "Для супу", "Інше"],
        "Качка": ["Ціла качка", "Грудка", "Стегно", "Крило", "Спина", "Шия", "Качиний жир", "Печінка", "Фарш", "Для супу", "Інше"],
        "Свинина": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Шинка", "Фарш", "Для супу", "Інше"],
        "Ягнятина": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Баранина": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Телятина": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Яловичина": ["Філей", "Стейк", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Кролик": ["Задні лапи", "Передні лапи", "Спинка", "Ребра", "Для супу", "Інше"],
        "Перепілка": ["Ціла", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Фазан": ["Цілий", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Куріпка": ["Ціла", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Голуб": ["Цілий", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Заєць": ["Задні лапи", "Передні лапи", "Спинка", "Ребра", "Інше"],
        "Дика качка": ["Ціла", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Дика гуска": ["Ціла", "Грудка", "Гомілки", "Крила", "Печінка", "Інше"],
        "Олень": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Косуля": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Дикий кабан": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Лось": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Північний олень": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Бізон": ["Філе", "Стейк", "Окост", "Шия", "Лопатка", "Грудинка", "Ребра", "Голяшка", "Фарш", "Для супу", "Інше"],
        "Верблюд": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Горб", "Ребра", "Фарш", "Для супу", "Інше"],
        "Лама": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Ребра", "Фарш", "Для супу", "Інше"],
        "Альпака": ["Філе", "Котлета", "Окост", "Шия", "Лопатка", "Ребра", "Фарш", "Для супу", "Інше"],
        "Кенгуру": ["Філе", "Стейк", "Окост", "Шия", "Лопатка", "Хвіст", "Фарш", "Для супу", "Інше"],
        "Крокодил/Алігатор": ["Хвіст", "Філе", "Гомілки", "Інше"],
        "Ящірка": ["Хвіст", "Спина", "Гомілки", "Інше"],
        "Змія": ["Кільця", "Інше"],
        "Морська": ["Філе", "Стейк", "Ціла риба", "Філе зі шкірою", "Філе без шкіри", "Шматки", "Для супу", "Інше"],
        "Прісноводна": ["Філе", "Стейк", "Ціла риба", "Філе зі шкірою", "Філе без шкіри", "Шматки", "Для супу", "Інше"],
        "Морепродукти": ["Креветки", "Кальмар", "Мідії", "Устриці", "Гребінці", "Краби", "Восьминіг", "Каракатиця", "Інше"],
        "Молоко": ["Цільне", "Знежирене", "Пастеризоване", "Стерилізоване", "Кип'ячене", "Згущене", "Сухе", "Інше"],
        "Молочні переробки": ["Сир", "Сир домашній", "Сметана", "Йогурт", "Кефір", "Масло", "Сирний крем", "Інше"],
        "Свіжі": ["Цілі", "Нарізані", "Виміті", "Очищені", "Терті", "Інше"],
        "Термічно оброблені": ["Варені", "Тушковані", "Смажені", "Запечені", "Приготовані на пару", "Інше"],
        "Заморожені": ["Цілі", "Нарізані", "Суміш", "Пюре", "Інше"],
        "Фрукти": ["Цілі", "Нарізані", "Очищені", "Без кісточок", "Консервовані", "Сушені", "Інше"],
        "Тісто": ["Дріжджове", "Пісочне", "Листкове", "Для млинців", "Для піци", "Для макарон", "Інше"],
        "Солодощі": ["Шоколад", "Цукерки", "Печиво", "Торти", "Випічка", "Морозиво", "Вафлі", "Інше"],
        "Вода": ["Газована", "Негазована", "Мінеральна", "Ароматизована", "Інше"],
        "Вино": ["Червоне", "Біле", "Рожеве", "Ігристe", "Солодке", "Сухе", "Напівсухе", "Інше"],
        "Сік": ["Яблучний", "Апельсиновий", "Виноградний", "Томатний", "Мультифрукт", "З м'якоттю", "Без м'якоті", "Інше"],
        "Міцні напої": ["Горілка", "Віскі", "Коньяк", "Ром", "Джин", "Текіла", "Лікер", "Інше"],
        "Пиво": ["Світле", "Темне", "Пшеничне", "Крафтове", "Безалкогольне", "Інше"],
        "Санітарія": ["Для ванної", "Для туалету", "Для умивальника", "Універсальний", "Антибактеріальний", "Інше"],
        "Особиста гігієна": ["Мило", "Шампунь", "Гель для душу", "Дезодорант", "Зубна паста", "Бритва", "Крем", "Інше"],
        "Приладдя": ["Відро", "Швабра", "Ганчірка", "Губка", "Щітка", "Рукавиці", "Інше"],
        "Інше": ["Примітка: введіть назву продукту"]
    },
    
    // ===== RUSKI =====
    ru: {
        "Курица": ["Целая курица", "Грудка", "Бедро", "Голень", "Крыло", "Филе", "Спина", "Медальоны", "Наггетсы", "Панированное", "Фарш", "Для супа", "Другое"],
        "Индейка": ["Целая индейка", "Грудка", "Бедро", "Голень", "Крыло", "Филе", "Спина", "Медальоны", "Для супа", "Фарш", "Другое"],
        "Гусь": ["Целая гусь", "Грудка", "Бедро", "Голень", "Крыло", "Спина", "Шея", "Печень", "Гусиный жир", "Фарш", "Для супа", "Другое"],
        "Утка": ["Целая утка", "Грудка", "Бедро", "Голень", "Крыло", "Спина", "Шея", "Утиный жир", "Печень", "Фарш", "Для супа", "Другое"],
        "Свинина": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Подплечный край", "Фарш", "Для супа", "Другое"],
        "Баранина": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Овца": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Телятина": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Говядина": ["Вырезка", "Стейк", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Кролик": ["Задние лапы", "Передние лапы", "Спинка", "Ребра", "Для супа", "Другое"],
        "Перепел": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Фазан": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Куропатка": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Голубь": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Заяц": ["Задние лапы", "Передние лапы", "Спинка", "Ребра", "Другое"],
        "Дикая утка": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Дикий гусь": ["Целая тушка", "Грудка", "Бедра", "Крылья", "Печень", "Другое"],
        "Олень": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Косуля": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Кабан": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Лось": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Северный олень": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Бизон": ["Вырезка", "Стейк", "Окорок", "Шея", "Лопатка", "Грудинка", "Ребра", "Рулька", "Фарш", "Для супа", "Другое"],
        "Верблюд": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Горб", "Ребра", "Фарш", "Для супа", "Другое"],
        "Лама": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Ребра", "Фарш", "Для супа", "Другое"],
        "Альпака": ["Вырезка", "Корейка", "Окорок", "Шея", "Лопатка", "Ребра", "Фарш", "Для супа", "Другое"],
        "Кенгуру": ["Вырезка", "Стейк", "Окорок", "Шея", "Лопатка", "Хвост", "Фарш", "Для супа", "Другое"],
        "Крокодил/Аллигатор": ["Хвост", "Филе", "Ноги", "Другое"],
        "Ящерица": ["Хвост", "Спина", "Ноги", "Другое"],
        "Змея": ["Кольца", "Другое"],
        "Морская": ["Филе", "Стейк", "Целая рыба", "Филе с кожей", "Филе без кожи", "Куски", "Для супа", "Другое"],
        "Пресноводная": ["Филе", "Стейк", "Целая рыба", "Филе с кожей", "Филе без кожи", "Куски", "Для супа", "Другое"],
        "Морепродукты": ["Креветки", "Кальмары", "Мидии", "Устрицы", "Гребешки", "Крабы", "Осьминоги", "Каракатицы", "Другое"],
        "Молоко": ["Цельное", "Обезжиренное", "Пастеризованное", "Стерилизованное", "Топленое", "Сгущенное", "Сухое", "Другое"],
        "Молочные переработки": ["Сыр", "Творог", "Сметана", "Йогурт", "Кефир", "Ряженка", "Сливочное масло", "Творожный сыр", "Другое"],
        "Свежие": ["Целые", "Нарезанные", "Вымытые", "Чищенные", "Натертые", "Другое"],
        "Термически обработанные": ["Вареные", "Тушеные", "Жареные", "Запеченные", "Приготовленные на пару", "Другое"],
        "Замороженные": ["Целые", "Нарезанные", "Смесь", "Пюре", "Другое"],
        "Фрукты": ["Целые", "Нарезанные", "Очищенные", "Без косточек", "Консервированные", "Сушеные", "Другое"],
        "Тесто": ["Дрожжевое", "Песочное", "Слоеное", "Блинное", "Для пиццы", "Для пасты", "Другое"],
        "Сладости": ["Шоколад", "Конфеты", "Печенье", "Торты", "Пирожные", "Мороженое", "Вафли", "Другое"],
        "Вода": ["Газированная", "Негазированная", "Минеральная", "Ароматизированная", "Другое"],
        "Вино": ["Красное", "Белое", "Розовое", "Игристое", "Сладкое", "Сухое", "Полусухое", "Другое"],
        "Сок": ["Яблочный", "Апельсиновый", "Виноградный", "Томатный", "Мультифрукт", "С мякотью", "Без мякоти", "Другое"],
        "Крепкие напитки": ["Водка", "Виски", "Коньяк", "Ром", "Джин", "Текила", "Ликер", "Другое"],
        "Пиво": ["Светлое", "Темное", "Пшеничное", "Крафтовое", "Безалкогольное", "Другое"],
        "Сантехника": ["Для ванной", "Для туалета", "Для раковины", "Универсальное", "Антибактериальное", "Другое"],
        "Личная гигиена": ["Мыло", "Шампунь", "Гель для душа", "Дезодорант", "Зубная паста", "Бритва", "Крем", "Другое"],
        "Оборудование": ["Ведро", "Швабра", "Тряпка", "Губка", "Щетка", "Перчатки", "Другое"],
        "Другое": ["Примечание: введите название продукта"]
    },
    
    // ===== KINESKI (skraćeno) =====
    zh: {
        "鸡": ["整鸡", "鸡胸", "鸡腿", "鸡翅", "鸡柳", "鸡背", "鸡块", "鸡米花", "炸鸡排", "鸡绞肉", "汤用", "其他"],
        "火鸡": ["整火鸡", "火鸡胸", "火鸡腿", "火鸡翅", "火鸡柳", "火鸡背", "火鸡块", "汤用", "火鸡绞肉", "其他"],
        "鹅": ["整鹅", "鹅胸", "鹅腿", "鹅翅", "鹅背", "鹅颈", "鹅肝", "鹅油", "鹅绞肉", "汤用", "其他"],
        "鸭": ["整鸭", "鸭胸", "鸭腿", "鸭翅", "鸭背", "鸭颈", "鸭油", "鸭肝", "鸭绞肉", "汤用", "其他"],
        "猪肉": ["里脊", "排骨", "猪腿", "猪颈", "猪肩", "猪胸", "猪肋", "猪蹄", "猪绞肉", "汤用", "其他"],
        "羊肉": ["里脊", "排骨", "羊腿", "羊颈", "羊肩", "羊胸", "羊肋", "羊蹄", "羊绞肉", "汤用", "其他"],
        "牛肉": ["里脊", "牛排", "牛腿", "牛颈", "牛肩", "牛胸", "牛肋", "牛蹄", "牛绞肉", "汤用", "其他"],
        "兔肉": ["后腿", "前腿", "兔背", "兔肋", "汤用", "其他"],
        "鹌鹑": ["整只", "鹌鹑胸", "鹌鹑腿", "鹌鹑翅", "鹌鹑肝", "其他"],
        "野鸡": ["整只", "野鸡胸", "野鸡腿", "野鸡翅", "野鸡肝", "其他"],
        "鹧鸪": ["整只", "鹧鸪胸", "鹧鸪腿", "鹧鸪翅", "鹧鸪肝", "其他"],
        "鸽子": ["整只", "鸽子胸", "鸽子腿", "鸽子翅", "鸽子肝", "其他"],
        "野兔": ["后腿", "前腿", "兔背", "兔肋", "其他"],
        "野鸭": ["整只", "野鸭胸", "野鸭腿", "野鸭翅", "野鸭肝", "其他"],
        "野鹅": ["整只", "野鹅胸", "野鹅腿", "野鹅翅", "野鹅肝", "其他"],
        "鹿": ["里脊", "鹿排", "鹿腿", "鹿颈", "鹿肩", "鹿胸", "鹿肋", "鹿蹄", "鹿绞肉", "汤用", "其他"],
        "狍子": ["里脊", "狍子排", "狍子腿", "狍子颈", "狍子肩", "狍子胸", "狍子肋", "狍子蹄", "狍子绞肉", "汤用", "其他"],
        "野猪": ["里脊", "野猪排", "野猪腿", "野猪颈", "野猪肩", "野猪胸", "野猪肋", "野猪蹄", "野猪绞肉", "汤用", "其他"],
        "驼鹿": ["里脊", "驼鹿排", "驼鹿腿", "驼鹿颈", "驼鹿肩", "驼鹿胸", "驼鹿肋", "驼鹿蹄", "驼鹿绞肉", "汤用", "其他"],
        "海鱼": ["鱼片", "鱼排", "整鱼", "带皮鱼片", "去皮鱼片", "鱼块", "汤用", "其他"],
        "淡水鱼": ["鱼片", "鱼排", "整鱼", "带皮鱼片", "去皮鱼片", "鱼块", "汤用", "其他"],
        "海鲜": ["虾", "鱿鱼", "蛤蜊", "牡蛎", "扇贝", "螃蟹", "章鱼", "墨鱼", "其他"],
        "牛奶": ["全脂", "脱脂", "巴氏杀菌", "灭菌", "煮沸", "炼乳", "奶粉", "其他"],
        "乳制品加工": ["奶酪", "干酪", "酸奶油", "酸奶", "开菲尔", "黄油", "奶油奶酪", "其他"],
        "新鲜": ["整颗", "切片", "洗净", "去皮", "擦丝", "其他"],
        "热处理": ["煮熟", "炖煮", "油炸", "烘烤", "蒸煮", "其他"],
        "冷冻": ["整颗", "切片", "混合", "泥状", "其他"],
        "水果": ["整颗", "切片", "去皮", "去核", "罐头", "干果", "其他"],
        "面团": ["酵母面团", "酥皮面团", "千层酥皮", "煎饼面糊", "披萨面团", "意大利面团", "其他"],
        "糖果": ["巧克力", "糖果", "饼干", "蛋糕", "糕点", "冰淇淋", "华夫饼", "其他"],
        "水": ["气泡水", "静水", "矿泉水", "调味水", "其他"],
        "酒": ["红酒", "白酒", "桃红", "起泡酒", "甜酒", "干酒", "半干", "其他"],
        "果汁": ["苹果汁", "橙汁", "葡萄汁", "番茄汁", "混合果汁", "带果肉", "无果肉", "其他"],
        "烈酒": ["伏特加", "威士忌", "干邑", "朗姆酒", "金酒", "龙舌兰", "利口酒", "其他"],
        "啤酒": ["淡啤", "黑啤", "小麦啤", "精酿", "无酒精", "其他"],
        "卫生": ["浴室用", "厕所用", "洗手池用", "通用", "抗菌", "其他"],
        "个人卫生": ["肥皂", "洗发水", "沐浴露", "除臭剂", "牙膏", "剃须刀", "面霜", "其他"],
        "设备": ["桶", "拖把", "布", "海绵", "刷子", "手套", "其他"],
        "其他": ["注：输入产品名称"]
    },
    
    // ===== ŠPANSKI (skraćeno) =====
    es: {
        "Pollo": ["Pollo entero", "Pechuga", "Muslo", "Ala", "Filete", "Espalda", "Medallones", "Nuggets", "Milanesa", "Carne molida", "Para sopa", "Otro"],
        "Pavo": ["Pavo entero", "Pechuga", "Muslo", "Ala", "Filete", "Espalda", "Medallones", "Para sopa", "Carne molida", "Otro"],
        "Ganso": ["Ganso entero", "Pechuga", "Muslo", "Ala", "Espalda", "Cuello", "Hígado", "Grasa de ganso", "Carne molida", "Para sopa", "Otro"],
        "Pato": ["Pato entero", "Pechuga", "Muslo", "Ala", "Espalda", "Cuello", "Grasa de pato", "Hígado", "Carne molida", "Para sopa", "Otro"],
        "Cerdo": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Jamón", "Carne molida", "Para sopa", "Otro"],
        "Cordero": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Res": ["Lomo", "Bistec", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Ternera": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Conejo": ["Patas traseras", "Patas delanteras", "Lomo", "Costillas", "Para sopa", "Otro"],
        "Codorniz": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Faisán": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Perdiz": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Paloma": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Liebre": ["Patas traseras", "Patas delanteras", "Lomo", "Costillas", "Otro"],
        "Pato salvaje": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Ganso salvaje": ["Entera", "Pechuga", "Muslos", "Alas", "Hígado", "Otro"],
        "Ciervo": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Corzo": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Jabalí": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Alce": ["Lomo", "Chuleta", "Pierna", "Cuello", "Paleta", "Pecho", "Costilla", "Codillo", "Carne molida", "Para sopa", "Otro"],
        "Mar": ["Filete", "Filete con piel", "Filete sin piel", "Entero", "Trozos", "Para sopa", "Otro"],
        "Agua dulce": ["Filete", "Filete con piel", "Filete sin piel", "Entero", "Trozos", "Para sopa", "Otro"],
        "Mariscos": ["Camarones", "Calamar", "Mejillones", "Ostras", "Vieiras", "Cangrejos", "Pulpo", "Sepia", "Otro"],
        "Leche": ["Entera", "Descremada", "Pasteurizada", "Esterilizada", "Hervida", "Condensada", "En polvo", "Otro"],
        "Procesamiento lácteo": ["Queso", "Requesón", "Crema agria", "Yogur", "Kéfir", "Mantequilla", "Queso crema", "Otro"],
        "Frescas": ["Enteras", "Cortadas", "Lavadas", "Peladas", "Ralladas", "Otro"],
        "Tratadas térmicamente": ["Cocidas", "Estofadas", "Fritas", "Horneadas", "Al vapor", "Otro"],
        "Congeladas": ["Enteras", "Cortadas", "Mezcla", "Puré", "Otro"],
        "Frutas": ["Enteras", "Cortadas", "Peladas", "Sin semillas", "Enlatadas", "Secas", "Otro"],
        "Masa": ["Levadura", "Quebrada", "Hojaldre", "Para panqueques", "Para pizza", "Para pasta", "Otro"],
        "Dulces": ["Chocolate", "Caramelos", "Galletas", "Pasteles", "Tortas", "Helado", "Wafles", "Otro"],
        "Agua": ["Con gas", "Sin gas", "Mineral", "Saborizada", "Otro"],
        "Vino": ["Tinto", "Blanco", "Rosado", "Espumoso", "Dulce", "Seco", "Semiseco", "Otro"],
        "Jugo": ["Manzana", "Naranja", "Uva", "Tomate", "Multifruta", "Con pulpa", "Sin pulpa", "Otro"],
        "Licores": ["Vodka", "Whisky", "Coñac", "Ron", "Ginebra", "Tequila", "Licor", "Otro"],
        "Cerveza": ["Clara", "Oscura", "Trigo", "Artesanal", "Sin alcohol", "Otro"],
        "Sanitario": ["Para baño", "Para inodoro", "Para lavabo", "Universal", "Antibacterial", "Otro"],
        "Higiene personal": ["Jabón", "Champú", "Gel de baño", "Desodorante", "Pasta dental", "Maquinilla", "Crema", "Otro"],
        "Equipo": ["Cubo", "Trapeador", "Paño", "Esponja", "Cepillo", "Guantes", "Otro"],
        "Otro": ["Nota: Ingrese el nombre del producto"]
    },
    
    // ===== PORTUGALSKI (skraćeno) =====
    pt: {
        "Frango": ["Frango grelhado", "Frango inteiro", "Coxa inteira", "Sobrecoxa", "Coxinha", "Peito", "Filé", "Costas", "Asas", "Medalhões", "Nuggets", "Bife empanado", "Moído", "Para sopa", "Outro"],
        "Peru": ["Coxa inteira", "Sobrecoxa", "Coxinha", "Coxa enrolada", "Bifes de coxa", "Peito", "Asas", "Costas", "Pontas de asa", "Para sopa", "Moído", "Outro"],
        "Ganso": ["Peito", "Sobrecoxa", "Coxinha", "Asas", "Costas", "Pescoço", "Fígado (foie gras)", "Banha de ganso", "Moído", "Para sopa", "Outro"],
        "Pato": ["Peito", "Sobrecoxa", "Coxinha", "Asas", "Costas", "Pescoço", "Banha de pato", "Moído", "Fígado", "Para sopa", "Outro"],
        "Porco": ["Bife", "Costeleta", "Pescoço", "Pernil", "Lombo", "Costelas", "Barriga", "Paleta", "Espádua", "Jarret", "Moído", "Picado", "Para sopa", "Outro"],
        "Cordeiro": ["Cabeça", "Pescoço", "Paleta", "Lombo", "Peito", "Rim", "Pernil", "Jarret", "Outro"],
        "Boi": ["Bife", "Pescoço", "Peito", "Paleta", "Jarret", "Costelas", "Fralda", "T-bone", "Alcatra", "Rib-eye", "Rabo", "Outro"],
        "Coelho": ["Perna traseira", "Perna dianteira", "Filé do lombo", "Costelas", "Outro"],
        "Codorna": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Faisão": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Perdiz": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Pato selvagem": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Ganso selvagem": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Lebre": ["Perna traseira", "Perna dianteira", "Filé do lombo", "Costelas", "Outro"],
        "Pombo": ["Carne inteira", "Peito (filés)", "Coxas", "Fígado", "Outro"],
        "Cervo": ["Perna", "Filé (lombo)", "Bife", "Costelas", "Peito", "Paleta", "Jarrete", "Picado", "Outro"],
        "Corça": ["Perna", "Filé (lombo)", "Bife", "Costelas", "Peito", "Paleta", "Jarrete", "Picado", "Outro"],
        "Cabra selvagem": ["Perna", "Filé (lombo)", "Bife", "Costelas", "Peito", "Paleta", "Jarrete", "Picado", "Outro"],
        "Alce": ["Perna", "Filé (lombo)", "Bife", "Costelas", "Peito", "Paleta", "Jarrete", "Picado", "Outro"],
        "Rena": ["Perna", "Filé (lombo)", "Bife", "Costelas", "Peito", "Paleta", "Jarrete", "Picado", "Outro"],
        "Javali": ["Perna", "Paleta", "Costelas", "Bacon", "Jarrete", "Pescoço", "Cabeça", "Outro"],
        "Bisão": ["Perna", "Paleta", "Bife", "Alcatra", "Costelas", "Lombo", "Pescoço", "Jarrete", "Outro"],
        "Camelo": ["Perna", "Paleta", "Filé (lombo)", "Filé (dorso)", "Costelas", "Peito", "Pescoço", "Corcova", "Outro"],
        "Lhama": ["Perna", "Paleta", "Filé (dorso e lombo)", "Costelas", "Pescoço", "Outro"],
        "Alpaca": ["Perna", "Paleta", "Filé (dorso e lombo)", "Costelas", "Pescoço", "Outro"],
        "Canguru": ["Perna", "Paleta", "Filé (dorso e lombo)", "Costelas", "Rabo", "Outro"],
        "Crocodilo/Jacaré": ["Rabo", "Filé (dorso)", "Coxas", "Outro"],
        "Lagarto": ["Rabo", "Dorso", "Coxas", "Outro"],
        "Cobra": ["Tronco (anéis)", "Outro"],
        "Mar": ["Salmão", "Atum", "Sardinha", "Bacalhau", "Pescada", "Cavala", "Robalo", "Dourada", "Linguado", "Arenque", "Anchova", "Outro"],
        "Água doce": ["Carpa", "Truta", "Bagre", "Percha", "Sander", "Tilápia", "Panga", "Esturjão", "Lúcio", "Carpa capim", "Pirarucu", "Outro"],
        "Frutos do mar": ["Camarão", "Lula", "Vieiras", "Amêijoas", "Mexilhões", "Ostras", "Caranguejo", "Polvo", "Ouriço", "Pepino do mar", "Abalone", "Outro"],
        "Leite": ["Leite", "Kefir", "Creme azedo", "Creme", "Creme de cozinha", "Outro"],
        "Processamento de leite": ["Queijo fresco", "Queijo jovem", "Queijo cremoso", "Gouda", "Edam", "Trappista", "Kashkaval", "Parmesão", "Gorgonzola", "Roquefort", "Halloumi", "Outro"],
        "Fresco": ["Ervilhas", "Feijão verde", "Couve-flor", "Brócolis", "Abóbora", "Tomate", "Pepino", "Pimentão", "Outro"],
        "Tratado termicamente": ["Ervilhas", "Feijão verde", "Milho", "Couve-flor", "Brócolis", "Pimentão", "Abobrinha", "Espinafre", "Outro"],
        "Congelado": ["Ervilhas", "Feijão verde", "Milho", "Couve-flor", "Brócolis", "Pimentão", "Abobrinha", "Espinafre", "Outro"],
        "Frutas": ["Damasco", "Pera", "Cereja", "Geleia de morango", "Geleia de ameixa", "Cereja doce", "Geleia de framboesa", "Marmelo", "Abacaxi", "Geleia de manga", "Outro"],
        "Vegetais": ["Picles", "Pimentão em conserva", "Purê de tomate", "Beterraba", "Ajvar", "Conservas", "Chucrute", "Outro"],
        "Massa": ["Pão", "Pão de centeio", "Ciabatta", "Pão de milho", "Baguete", "Farinha de trigo", "Farinha integral", "Farinha de trigo sarraceno", "Farinha de arroz", "Temperos", "Outro"],
        "Doces": ["Bolos", "Tortas", "Padaria", "Sorvete", "Chocolate", "Doces", "Outro"],
        "Água": ["Mineral", "Sem gás", "Com gás", "Outro"],
        "Vinho": ["Tinto", "Branco", "Rosé", "Outro"],
        "Suco": ["Fruta", "Vegetal", "Outro"],
        "Bebidas destiladas": ["Conhaque", "Vodka", "Uísque", "Outro"],
        "Cerveja": ["Escura", "Clara", "Outro"],
        "Sanitário": ["Limpa-vidros", "Detergente", "Limpa-pisos", "Limpa-banheiro", "Outro"],
        "Higiene pessoal": ["Desodorante", "Lâmina", "Maquiagem", "Sabão", "Xampu", "Creme", "Outro"],
        "Equipamento": ["Balde", "Pano", "Espanador", "Vassoura", "Outro"],
        "Outro": ["Nota: Digite o nome do produto"]
    },
    
    // ===== FRANCUSKI (skraćeno) =====
    fr: {
        "Poulet": ["Poulet entier", "Poitrine", "Cuisse", "Aile", "Filet", "Dos", "Médaillons", "Nuggets", "Escalope panée", "Viande hachée", "Pour soupe", "Autre"],
        "Dinde": ["Dinde entière", "Poitrine", "Cuisse", "Aile", "Filet", "Dos", "Médaillons", "Pour soupe", "Viande hachée", "Autre"],
        "Oie": ["Oie entière", "Poitrine", "Cuisse", "Aile", "Dos", "Cou", "Foie", "Graisse d'oie", "Viande hachée", "Pour soupe", "Autre"],
        "Canard": ["Canard entier", "Magret", "Cuisse", "Aile", "Dos", "Cou", "Graisse de canard", "Foie", "Viande hachée", "Pour soupe", "Autre"],
        "Porc": ["Filet", "Côtelette", "Jambon", "Échine", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Agneau": ["Filet", "Côtelette", "Gigot", "Collet", "Épaule", "Poitrine", "Côtes", "Souris", "Viande hachée", "Pour soupe", "Autre"],
        "Bœuf": ["Filet", "Entrecôte", "Rumsteck", "Collier", "Paleron", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Veau": ["Filet", "Côtelette", "Rognonnade", "Collet", "Épaule", "Poitrine", "Côtes", "Osso buco", "Viande hachée", "Pour soupe", "Autre"],
        "Lapin": ["Cuisses arrière", "Cuisses avant", "Râble", "Côtes", "Pour soupe", "Autre"],
        "Caille": ["Entière", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Faisan": ["Entier", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Perdrix": ["Entière", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Pigeon": ["Entier", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Lièvre": ["Cuisses arrière", "Cuisses avant", "Râble", "Côtes", "Autre"],
        "Canard sauvage": ["Entier", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Oie sauvage": ["Entière", "Poitrine", "Cuisses", "Ailes", "Foie", "Autre"],
        "Cerf": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Chevreuil": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Sanglier": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Élan": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Renne": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Bison": ["Filet", "Entrecôte", "Cuissot", "Collet", "Épaule", "Poitrine", "Côtes", "Jarret", "Viande hachée", "Pour soupe", "Autre"],
        "Chameau": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Bosse", "Côtes", "Viande hachée", "Pour soupe", "Autre"],
        "Lama": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Côtes", "Viande hachée", "Pour soupe", "Autre"],
        "Alpaga": ["Filet", "Côtelette", "Cuissot", "Collet", "Épaule", "Côtes", "Viande hachée", "Pour soupe", "Autre"],
        "Kangourou": ["Filet", "Steak", "Cuissot", "Collet", "Épaule", "Queue", "Viande hachée", "Pour soupe", "Autre"],
        "Crocodile/Alligator": ["Queue", "Filet", "Cuisses", "Autre"],
        "Lézard": ["Queue", "Dos", "Cuisses", "Autre"],
        "Serpent": ["Anneaux", "Autre"],
        "Mer": ["Filet", "Darnes", "Poisson entier", "Filet avec peau", "Filet sans peau", "Morceaux", "Pour soupe", "Autre"],
        "Eau douce": ["Filet", "Darnes", "Poisson entier", "Filet avec peau", "Filet sans peau", "Morceaux", "Pour soupe", "Autre"],
        "Fruits de mer": ["Crevettes", "Calmar", "Moules", "Huîtres", "Coquilles Saint-Jacques", "Crabes", "Poulpe", "Seiche", "Autre"],
        "Lait": ["Entier", "Écrémé", "Pasteurisé", "Stérilisé", "Bouilli", "Condensé", "En poudre", "Autre"],
        "Transformation laitière": ["Fromage", "Fromage blanc", "Crème fraîche", "Yaourt", "Kéfir", "Beurre", "Fromage à tartiner", "Autre"],
        "Frais": ["Entiers", "Coupés", "Lavés", "Pelés", "Râpés", "Autre"],
        "Traité thermiquement": ["Cuits", "Étuvés", "Frits", "Rôtis", "Vapeur", "Autre"],
        "Congelé": ["Entiers", "Coupés", "Mélange", "Purée", "Autre"],
        "Fruits": ["Entiers", "Tranchés", "Pelés", "Sans pépins", "En conserve", "Séchés", "Autre"],
        "Pâte": ["Pâte à levure", "Pâte brisée", "Pâte feuilletée", "Pâte à crêpes", "Pâte à pizza", "Pâte à pâtes", "Autre"],
        "Sucreries": ["Chocolat", "Bonbons", "Biscuits", "Gâteaux", "Pâtisseries", "Glace", "Gaufres", "Autre"],
        "Eau": ["Pétillante", "Plate", "Minérale", "Aromatisée", "Autre"],
        "Vin": ["Rouge", "Blanc", "Rosé", "Mousseux", "Doux", "Sec", "Demi-sec", "Autre"],
        "Jus": ["Pomme", "Orange", "Raisin", "Tomate", "Multifruits", "Avec pulpe", "Sans pulpe", "Autre"],
        "Spiritueux": ["Vodka", "Whisky", "Cognac", "Rhum", "Gin", "Tequila", "Liqueur", "Autre"],
        "Bière": ["Blonde", "Brune", "Blanche", "Artisanale", "Sans alcool", "Autre"],
        "Sanitaire": ["Pour salle de bain", "Pour toilettes", "Pour lavabo", "Universel", "Antibactérien", "Autre"],
        "Hygiène personnelle": ["Savon", "Shampooing", "Gel douche", "Déodorant", "Dentifrice", "Rasoir", "Crème", "Autre"],
        "Équipement": ["Seau", "Balai", "Chiffon", "Éponge", "Brosse", "Gants", "Autre"],
        "Autre": ["Note : Saisir le nom du produit"]
    }
};
function getProductPartsColors(partName) {
    return {
        background: '#ffffff',
        text: '#1a237e'
    };
}
